---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by xuyuan.
--- DateTime: 2021/8/2 2:10
---

local CGEntitySetVisible = CGEntitySetVisible or {}
CGEntitySetVisible.__index = CGEntitySetVisible

function CGEntitySetVisible.new()
    local self = setmetatable({}, CGEntitySetVisible)
    self.inputs = {}
    self.outputs = {}
    self.nexts = {}
    return self
end

function CGEntitySetVisible:setNext(index, func)
    self.nexts[index] = func
end

function CGEntitySetVisible:setInput(index, func)
    self.inputs[index] = func
end

function CGEntitySetVisible:getOutput(index, func)
    if self.inputs[2] then
        return self.inputs[2]()
    end
    return nil
end

function CGEntitySetVisible:execute(index)
    if self.inputs[1] ~= nil then
        local object = self.inputs[1]()
        local visible = self.inputs[2]()
        if object ~= nil and object:isInstanceOf("Entity") then
            object.visible = visible
        end
    end
    if self.nexts[0] then
        self.nexts[0]()
    end
end

return CGEntitySetVisible
